# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['top' 'top' '2' '4.5' 'bottom' 'top' 'top' 'top' 'top' '2']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [3]:
print(np.random.choice(list(range(10))))

6


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [4]:
print(np.random.choice(list(range(10)), size=(4, 6)))

[[2 6 3 8 0 9]
 [5 4 6 6 2 4]
 [4 1 0 1 5 5]
 [1 7 3 5 5 3]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 2 0 2 4 1 3 2 4 1]


Згенеруйте одну випадкову цифру.

In [6]:
print(np.random.randint(low=0, high=10))

7


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [7]:
print(np.random.randint(low=10, high=100, size=(4, 5)))

[[81 95 16 58 72]
 [61 62 43 36 11]
 [79 45 97 83 96]
 [87 77 75 57 26]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.5311285164834063


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [9]:
print(np.random.sample(size=(3, 4)))

[[0.05600608 0.38789183 0.53779093 0.74850602]
 [0.51726816 0.5164903  0.1923797  0.02740415]
 [0.26528676 0.08303455 0.92664029 0.38366746]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [10]:
a = 3
b = 5

In [11]:
print(np.random.sample(size=10))

[0.9936068  0.45041276 0.1355302  0.5733524  0.58394594 0.44975252
 0.63148497 0.32007323 0.47315296 0.5677449 ]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[6 8 5 7 0 4 9 2 3 1]


Перетасуйте матрицю $M$.

In [13]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
np.random.shuffle(M)
print(M)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]


In [15]:
# або 
M = M.flatten()
np.random.shuffle(M)
M = M.reshape((4, 5))
print(M)

[[13 14 12  2 11]
 [17  7  8  0 16]
 [10  3  6  1 18]
 [15 19  9  4  5]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [16]:
np.random.seed(42)

In [17]:
print(np.random.randint(10))

6


In [18]:
print(np.random.randint(10))

3


In [19]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [20]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [21]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H']


In [22]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [23]:
p=0.5
n=100
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
heads = list(tosses).count("H")
tails = list(tosses).count("T")
print("{} heads and {} tails".format(heads,tails))

50 heads and 50 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [24]:
n = 100
tosses = np.random.randint(low=0, high=2, size=n)
heads = list(tosses).count(1)
tails = list(tosses).count(0)
print("{} heads and {} tails".format(heads,tails))


49 heads and 51 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [25]:
n = 100
tosses = np.random.sample(size=n)
heads = tosses[tosses >= 0.5]
tails = tosses[tosses < 0.5]
print("{} heads and {} tails".format(len(heads), len(tails)))


59 heads and 41 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [26]:
for n in (10,50,100,250,500,1000,2500,5000,10000):
    tosses = np.random.randint(low=0, high=2, size=n)
    heads = list(tosses).count(1) # Герб
    tails = list(tosses).count(0)
    print("For n = {} probability of Head is {}".format(n,heads/n))

For n = 10 probability of Head is 0.5
For n = 50 probability of Head is 0.6
For n = 100 probability of Head is 0.54
For n = 250 probability of Head is 0.452
For n = 500 probability of Head is 0.492
For n = 1000 probability of Head is 0.473
For n = 2500 probability of Head is 0.5084
For n = 5000 probability of Head is 0.497
For n = 10000 probability of Head is 0.5003


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [27]:
sides = tuple(range(1, 7))
n = 60
tosses = np.random.randint(low=1, high=7, size=n)
for side in sides:
    print("For side {} got {} flips.".format(side, list(tosses).count(side)))

For side 1 got 11 flips.
For side 2 got 6 flips.
For side 3 got 13 flips.
For side 4 got 8 flips.
For side 5 got 6 flips.
For side 6 got 16 flips.


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [28]:
for n in (10,50,100,250,500,1000,2500,5000,10000):
    print("N =", n)
    tosses = np.random.randint(low=1, high=7, size=n)
    for side in sides:
        print("\tFor side {} probability is {}.".format(side, list(tosses).count(side)/n))

N = 10
	For side 1 probability is 0.2.
	For side 2 probability is 0.1.
	For side 3 probability is 0.2.
	For side 4 probability is 0.2.
	For side 5 probability is 0.2.
	For side 6 probability is 0.1.
N = 50
	For side 1 probability is 0.16.
	For side 2 probability is 0.14.
	For side 3 probability is 0.2.
	For side 4 probability is 0.18.
	For side 5 probability is 0.2.
	For side 6 probability is 0.12.
N = 100
	For side 1 probability is 0.19.
	For side 2 probability is 0.16.
	For side 3 probability is 0.15.
	For side 4 probability is 0.17.
	For side 5 probability is 0.1.
	For side 6 probability is 0.23.
N = 250
	For side 1 probability is 0.16.
	For side 2 probability is 0.148.
	For side 3 probability is 0.164.
	For side 4 probability is 0.2.
	For side 5 probability is 0.196.
	For side 6 probability is 0.132.
N = 500
	For side 1 probability is 0.164.
	For side 2 probability is 0.158.
	For side 3 probability is 0.15.
	For side 4 probability is 0.18.
	For side 5 probability is 0.14.
	For side

## 5 Колода карт
### 5.1 Реалізація

In [29]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = sorted([(Rank, Suit) for Rank in Ranks for Suit in Suits])
print(Cards)

[('1', '♠'), ('1', '♡'), ('1', '♢'), ('1', '♣'), ('10', '♠'), ('10', '♡'), ('10', '♢'), ('10', '♣'), ('2', '♠'), ('2', '♡'), ('2', '♢'), ('2', '♣'), ('3', '♠'), ('3', '♡'), ('3', '♢'), ('3', '♣'), ('4', '♠'), ('4', '♡'), ('4', '♢'), ('4', '♣'), ('5', '♠'), ('5', '♡'), ('5', '♢'), ('5', '♣'), ('6', '♠'), ('6', '♡'), ('6', '♢'), ('6', '♣'), ('7', '♠'), ('7', '♡'), ('7', '♢'), ('7', '♣'), ('8', '♠'), ('8', '♡'), ('8', '♢'), ('8', '♣'), ('9', '♠'), ('9', '♡'), ('9', '♢'), ('9', '♣'), ('J', '♠'), ('J', '♡'), ('J', '♢'), ('J', '♣'), ('K', '♠'), ('K', '♡'), ('K', '♢'), ('K', '♣'), ('Q', '♠'), ('Q', '♡'), ('Q', '♢'), ('Q', '♣')]


In [30]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

1♠, 1♡, 1♢, 1♣, 10♠, 10♡, 10♢, 10♣, 2♠, 2♡, 2♢, 2♣, 3♠, 3♡, 3♢, 3♣, 4♠, 4♡, 4♢, 4♣, 5♠, 5♡, 5♢, 5♣, 6♠, 6♡, 6♢, 6♣, 7♠, 7♡, 7♢, 7♣, 8♠, 8♡, 8♢, 8♣, 9♠, 9♡, 9♢, 9♣, J♠, J♡, J♢, J♣, K♠, K♡, K♢, K♣, Q♠, Q♡, Q♢, Q♣


In [31]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♠1, ♠2, ♠4, ♠5, ♠8, ♠Q, ♠10, ♠9, ♠6, ♠J, ♠7, ♠K, ♠3
♡1, ♡2, ♡4, ♡5, ♡8, ♡Q, ♡10, ♡9, ♡6, ♡J, ♡7, ♡K, ♡3
♣1, ♣2, ♣4, ♣5, ♣8, ♣Q, ♣10, ♣9, ♣6, ♣J, ♣7, ♣K, ♣3
♢1, ♢2, ♢4, ♢5, ♢8, ♢Q, ♢10, ♢9, ♢6, ♢J, ♢7, ♢K, ♢3


In [32]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('Q', '♡'), ('8', '♡'), ('3', '♡'), ('5', '♡'), ('K', '♢'), ('4', '♣'), ('8', '♣'), ('K', '♣'), ('10', '♡'), ('6', '♢'), ('K', '♡'), ('4', '♠'), ('1', '♡'), ('6', '♣'), ('3', '♠'), ('Q', '♣'), ('8', '♢'), ('2', '♠'), ('1', '♢'), ('J', '♣'), ('J', '♡'), ('2', '♣'), ('2', '♢'), ('3', '♣'), ('7', '♣'), ('2', '♡'), ('4', '♢'), ('3', '♢'), ('9', '♠'), ('8', '♠'), ('6', '♡'), ('Q', '♢'), ('10', '♣'), ('4', '♡'), ('7', '♡'), ('J', '♢'), ('K', '♠'), ('10', '♠'), ('9', '♡'), ('7', '♢'), ('6', '♠'), ('J', '♠'), ('1', '♠'), ('Q', '♠'), ('9', '♣'), ('5', '♢'), ('10', '♢'), ('9', '♢'), ('5', '♠'), ('1', '♣'), ('5', '♣'), ('7', '♠')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [33]:
def check(a):
    target = ['2', '4', '6', '8', '10']
    return a[0] in target
cards = np.array(Cards)
for n in (10,50,100,250,500,1000,2500,5000,10000):
    choices = np.random.choice(list(range(len(Cards))), size=n)
    sad = cards[choices]
    sad = sad[np.apply_along_axis(check, 1, sad)]
    print('For n = {} probability of showing card with even number is {}'.format(n, len(sad)/n))

For n = 10 probability of showing card with even number is 0.4
For n = 50 probability of showing card with even number is 0.48
For n = 100 probability of showing card with even number is 0.28
For n = 250 probability of showing card with even number is 0.352
For n = 500 probability of showing card with even number is 0.37
For n = 1000 probability of showing card with even number is 0.35
For n = 2500 probability of showing card with even number is 0.386
For n = 5000 probability of showing card with even number is 0.393
For n = 10000 probability of showing card with even number is 0.3906


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [51]:
hands = [[] for i in range(4)]
for i, suit in enumerate(Suits):
    current_hand = [(suit, rank) for rank in Ranks]
    np.random.shuffle(current_hand)
    for h in range(4):
        card_num = 4 if i==h else 3
        hands[h] += current_hand[:card_num]
        current_hand = current_hand[card_num:]

for hand in hands:
    np.random.shuffle(hand)
    print(', '.join((suit+rank) for suit, rank in hand))


♣10, ♢8, ♣6, ♡8, ♠6, ♠4, ♣3, ♢10, ♠J, ♠K, ♡4, ♢1, ♡6
♣7, ♠5, ♣1, ♡Q, ♠7, ♢J, ♢7, ♡2, ♠10, ♣9, ♡10, ♢9, ♡7
♢K, ♣Q, ♡3, ♢Q, ♢5, ♠Q, ♣4, ♣K, ♠2, ♣2, ♠8, ♡9, ♡J
♠9, ♡1, ♠3, ♢6, ♣5, ♣8, ♢4, ♡K, ♢3, ♠1, ♡5, ♢2, ♣J


### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [114]:
def get_random_split(low, high):
    summ = 13
    ind = []
    while True:
        ind = np.random.randint(low=2, high=6, size=(3, 3))
        a_row = np.array([13 - np.apply_along_axis(sum, 0, ind)])
        if all(a_row[0] <= 5) and all(a_row[0] >= 2):
            ind = np.concatenate((ind, a_row), axis=0)
            a_col = np.array([13 - np.apply_along_axis(sum, 1, ind)])
            if all(a_col[0] <= 5) and all(a_col[0] >= 2):
                ind = np.concatenate((ind, a_col.T), axis=1)
                break
    
    return ind

In [117]:
hands = [[] for i in range(4)]
split = get_random_split(2, 5)
for i, suit in enumerate(Suits):
    current_hand = [(suit, rank) for rank in Ranks]
    np.random.shuffle(current_hand)
    for j, card_num in enumerate(split[i]):
        hands[j] += current_hand[:card_num]
        current_hand = current_hand[card_num:]

for hand in hands:
    np.random.shuffle(hand)
    print(', '.join((suit+rank) for suit, rank in hand))


♢Q, ♡9, ♡3, ♡1, ♠2, ♣4, ♢2, ♠5, ♣1, ♠9, ♠K, ♣3, ♣Q
♡K, ♢K, ♠6, ♡J, ♡Q, ♣6, ♢1, ♣9, ♡2, ♠4, ♣K, ♢6, ♣10
♢10, ♡8, ♠8, ♠Q, ♣5, ♢9, ♡10, ♢7, ♣7, ♣J, ♢3, ♠1, ♢5
♡5, ♡4, ♡7, ♢J, ♠J, ♠10, ♡6, ♣8, ♠7, ♢8, ♢4, ♠3, ♣2
